//guesing_game.cpp: Rishabh Dev
//Description: A game where user guesses the random number
//generated by the computer. the computer also gives hint.

#include <iostream>

//#include <>

using namespace std;

int main(){

    //initialze random time
    srand(time(NULL));

    //Generate random number between 1 to 100
    int rand_number = rand()%100 + 1;

    int user_guess;

    cout << "Guess our number(0 to 100) " << endl;
    
    do{
    if(!(cin >> user_guess)){
        cout << "Please enter only numbers.";
        cin.clear();
        cin.ignore(10000,'\n');
    }else{
        if(user_guess > rand_number){
            cout << "The secret number is lower than " << user_guess << endl;
        } else if(user_guess < rand_number){
            cout << "The secret number is higher than " << user_guess << endl;
        }
    }
    }while(user_guess != rand_number);

    //The loops ends when the user guesses the right answer
    cout << "Congratulations!";

    return 0;
}